import {
  canonicalApplicationSchemaDefaults,
  transferPackageManifestSchemaDefaults,
  universityMappingOverlaySchemaDefaults,
  type CanonicalApplicationV1,
  type TransferPackageManifestV1,
  type UniversityMappingOverlayV1,
} from "./contracts";

const CHECKSUM_A =
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const CHECKSUM_B =
  "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
const CHECKSUM_C =
  "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
const CHECKSUM_D =
  "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
const CHECKSUM_E =
  "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";

export const canonicalApplicationSamples: CanonicalApplicationV1[] = [
  {
    ...canonicalApplicationSchemaDefaults,
    applicationId: "app-scu-001",
    applicantId: "applicant-001",
    status: "submitted",
    submittedAt: "2026-03-10T09:00:00Z",
    personalDetails: {
      firstName: "Jamie",
      lastName: "Nguyen",
      preferredName: "Jay",
      email: "jamie.nguyen@example.edu",
      phone: "+61 400 000 001",
      citizenshipStatus: "permanent-resident",
    },
    residentialAddress: {
      formattedAddress: "12 River Street, Lismore NSW 2480, Australia",
      streetAddress: "12 River Street",
      suburb: "Lismore",
      state: "NSW",
      postcode: "2480",
      country: "Australia",
    },
    selectedCourse: {
      courseCode: "MBA-ONLINE",
      courseTitle: "Master of Business Administration",
      providerCode: "SCU",
      providerName: "Southern Coast University",
      intakeCode: "2026-T2",
      intakeLabel: "Trimester 2 2026",
      studyMode: "online",
    },
    qualifications: [
      {
        qualificationId: "qual-001",
        level: "bachelor",
        institutionName: "University of Newcastle",
        country: "Australia",
        courseName: "Bachelor of Commerce",
        startDate: "2018-02-01",
        endDate: "2021-11-30",
        completed: true,
        gradeAverage: "5.8/7",
        documentIds: ["doc-001", "doc-002"],
      },
    ],
    employmentHistory: [
      {
        experienceId: "exp-001",
        employerName: "Northwind Advisory",
        title: "Operations Analyst",
        employmentType: "full-time",
        startDate: "2022-01-10",
        currentRole: true,
        dutiesSummary: "Owns student operations reporting and vendor reconciliations.",
      },
    ],
    languageTests: [],
    documents: [
      {
        documentId: "doc-001",
        category: "transcript",
        filename: "commerce-transcript.pdf",
        contentType: "application/pdf",
        sizeBytes: 182200,
        checksumSha256: CHECKSUM_A,
        sourceUri: "s3://demo/scu/app-scu-001/commerce-transcript.pdf",
        uploadedAt: "2026-03-09T08:00:00Z",
        requiredForSubmission: true,
      },
      {
        documentId: "doc-002",
        category: "certificate",
        filename: "commerce-award.pdf",
        contentType: "application/pdf",
        sizeBytes: 90210,
        checksumSha256: CHECKSUM_B,
        sourceUri: "s3://demo/scu/app-scu-001/commerce-award.pdf",
        uploadedAt: "2026-03-09T08:01:00Z",
        requiredForSubmission: true,
      },
    ],
    metadata: {
      sourceApplicationRecordId: "local-001",
      partnerProfile: "southern-coast-online",
    },
  },
  {
    ...canonicalApplicationSchemaDefaults,
    applicationId: "app-tiu-002",
    applicantId: "applicant-002",
    status: "submitted",
    submittedAt: "2026-03-10T09:15:00Z",
    personalDetails: {
      firstName: "Priya",
      lastName: "Raman",
      email: "priya.raman@example.edu",
      citizenshipStatus: "international",
    },
    selectedCourse: {
      courseCode: "GC-PM",
      courseTitle: "Graduate Certificate in Project Management",
      providerCode: "TIU",
      providerName: "Tasman Institute of Technology",
      intakeCode: "2026-S1",
      intakeLabel: "Semester 1 2026",
      studyMode: "blended",
    },
    qualifications: [
      {
        qualificationId: "qual-002",
        level: "graduate-certificate",
        institutionName: "Monash University",
        country: "Australia",
        courseName: "Graduate Certificate in Analytics",
        startDate: "2023-02-01",
        endDate: "2023-11-15",
        completed: true,
        documentIds: ["doc-003"],
      },
      {
        qualificationId: "qual-003",
        level: "bachelor",
        institutionName: "Anna University",
        country: "India",
        courseName: "Bachelor of Engineering",
        startDate: "2016-07-01",
        endDate: "2020-05-31",
        completed: true,
        documentIds: ["doc-004"],
      },
    ],
    employmentHistory: [],
    languageTests: [
      {
        testId: "lang-001",
        provider: "IELTS",
        testName: "Academic IELTS",
        completedAt: "2025-09-01",
        overallScore: "7.5",
        documentIds: ["doc-005"],
      },
    ],
    documents: [
      {
        documentId: "doc-003",
        category: "transcript",
        filename: "analytics-transcript.pdf",
        contentType: "application/pdf",
        sizeBytes: 133200,
        checksumSha256: CHECKSUM_C,
        sourceUri: "s3://demo/tiu/app-tiu-002/analytics-transcript.pdf",
        uploadedAt: "2026-03-09T08:02:00Z",
      },
      {
        documentId: "doc-004",
        category: "certificate",
        filename: "engineering-award.pdf",
        contentType: "application/pdf",
        sizeBytes: 113000,
        checksumSha256: CHECKSUM_D,
        sourceUri: "s3://demo/tiu/app-tiu-002/engineering-award.pdf",
        uploadedAt: "2026-03-09T08:03:00Z",
      },
      {
        documentId: "doc-005",
        category: "language-test",
        filename: "ielts-result.pdf",
        contentType: "application/pdf",
        sizeBytes: 55210,
        checksumSha256: CHECKSUM_E,
        sourceUri: "s3://demo/tiu/app-tiu-002/ielts-result.pdf",
        uploadedAt: "2026-03-09T08:04:00Z",
      },
    ],
    metadata: {
      sourceApplicationRecordId: "local-002",
      partnerProfile: "tasman-import",
    },
  },
  {
    ...canonicalApplicationSchemaDefaults,
    applicationId: "app-hhi-003",
    applicantId: "applicant-003",
    status: "decisioned",
    submittedAt: "2026-03-10T09:30:00Z",
    personalDetails: {
      firstName: "Morgan",
      lastName: "Lee",
      email: "morgan.lee@example.edu",
      phone: "+61 400 000 003",
    },
    postalAddress: {
      formattedAddress: "PO Box 200, Southbank VIC 3006, Australia",
      country: "Australia",
    },
    selectedCourse: {
      courseCode: "BN-HEALTH",
      courseTitle: "Bachelor of Nursing",
      providerCode: "HHI",
      providerName: "Harbour Health Institute",
      intakeCode: "2026-AUG",
      intakeLabel: "August 2026",
      studyMode: "on-campus",
    },
    qualifications: [
      {
        qualificationId: "qual-004",
        level: "secondary",
        institutionName: "Melbourne Senior College",
        country: "Australia",
        courseName: "Victorian Certificate of Education",
        endDate: "2022-11-30",
        completed: true,
        documentIds: [],
      },
      {
        qualificationId: "qual-005",
        level: "certificate",
        institutionName: "TAFE Victoria",
        country: "Australia",
        courseName: "Certificate IV in Allied Health Assistance",
        startDate: "2023-02-01",
        endDate: "2023-10-31",
        completed: true,
        documentIds: ["doc-006"],
      },
    ],
    employmentHistory: [
      {
        experienceId: "exp-002",
        employerName: "City Aged Care",
        title: "Care Support Worker",
        employmentType: "part-time",
        startDate: "2024-02-01",
        currentRole: true,
      },
    ],
    languageTests: [],
    documents: [
      {
        documentId: "doc-006",
        category: "certificate",
        filename: "allied-health-cert.pdf",
        contentType: "application/pdf",
        sizeBytes: 78420,
        checksumSha256: CHECKSUM_A,
        sourceUri: "s3://demo/hhi/app-hhi-003/allied-health-cert.pdf",
        uploadedAt: "2026-03-09T08:05:00Z",
      },
      {
        documentId: "doc-007",
        category: "cv",
        filename: "morgan-lee-cv.pdf",
        contentType: "application/pdf",
        sizeBytes: 98312,
        checksumSha256: CHECKSUM_B,
        sourceUri: "s3://demo/hhi/app-hhi-003/morgan-lee-cv.pdf",
        uploadedAt: "2026-03-09T08:06:00Z",
      },
    ],
    metadata: {
      sourceApplicationRecordId: "local-003",
      partnerProfile: "harbour-health-file-drop",
    },
  },
];

export const transferPackageManifestSamples: TransferPackageManifestV1[] = [
  {
    ...transferPackageManifestSchemaDefaults,
    manifestId: "manifest-001",
    applicationId: "app-scu-001",
    decisionId: "decision-001",
    partnerId: "SCU",
    partnerName: "Southern Coast University",
    generatedAt: "2026-03-10T10:00:00Z",
    artifacts: [
      {
        artifactId: "artifact-001",
        artifactType: "csv",
        filename: "southern-coast-app-scu-001.csv",
        checksumSha256: CHECKSUM_C,
        byteSize: 2048,
        generatedAt: "2026-03-10T10:00:00Z",
      },
      {
        artifactId: "artifact-002",
        artifactType: "zip",
        filename: "southern-coast-app-scu-001-documents.zip",
        checksumSha256: CHECKSUM_D,
        byteSize: 561230,
        generatedAt: "2026-03-10T10:00:10Z",
      },
    ],
    documents: [
      {
        documentId: "doc-001",
        logicalPath: "documents/transcripts/commerce-transcript.pdf",
        filename: "commerce-transcript.pdf",
        checksumSha256: CHECKSUM_A,
        byteSize: 182200,
        category: "transcript",
      },
      {
        documentId: "doc-002",
        logicalPath: "documents/certificates/commerce-award.pdf",
        filename: "commerce-award.pdf",
        checksumSha256: CHECKSUM_B,
        byteSize: 90210,
        category: "certificate",
      },
    ],
    handoff: {
      handoffMode: "sftp",
      destinationRef: "sftp://scu.example.edu/imports",
      encryptionProfile: "zip-aes256",
      idempotencyKey: "decision-001:SCU",
    },
  },
  {
    ...transferPackageManifestSchemaDefaults,
    manifestId: "manifest-002",
    applicationId: "app-tiu-002",
    decisionId: "decision-002",
    partnerId: "TIU",
    partnerName: "Tasman Institute of Technology",
    generatedAt: "2026-03-10T10:15:00Z",
    artifacts: [
      {
        artifactId: "artifact-003",
        artifactType: "xml",
        filename: "tasman-application.xml",
        checksumSha256: CHECKSUM_E,
        byteSize: 4096,
        generatedAt: "2026-03-10T10:15:00Z",
      },
    ],
    documents: [
      {
        documentId: "doc-003",
        logicalPath: "attachments/analytics-transcript.pdf",
        filename: "analytics-transcript.pdf",
        checksumSha256: CHECKSUM_C,
        byteSize: 133200,
        category: "transcript",
      },
    ],
    handoff: {
      handoffMode: "manual-import",
      destinationRef: "tasman-import-template-v3",
      encryptionProfile: "none",
      idempotencyKey: "decision-002:TIU",
    },
  },
  {
    ...transferPackageManifestSchemaDefaults,
    manifestId: "manifest-003",
    applicationId: "app-hhi-003",
    decisionId: "decision-003",
    partnerId: "HHI",
    partnerName: "Harbour Health Institute",
    generatedAt: "2026-03-10T10:30:00Z",
    artifacts: [
      {
        artifactId: "artifact-004",
        artifactType: "csv",
        filename: "harbour-health-bn-health.csv",
        checksumSha256: CHECKSUM_D,
        byteSize: 1782,
        generatedAt: "2026-03-10T10:30:00Z",
      },
    ],
    documents: [
      {
        documentId: "doc-006",
        logicalPath: "evidence/allied-health-cert.pdf",
        filename: "allied-health-cert.pdf",
        checksumSha256: CHECKSUM_A,
        byteSize: 78420,
        category: "certificate",
      },
      {
        documentId: "doc-007",
        logicalPath: "evidence/morgan-lee-cv.pdf",
        filename: "morgan-lee-cv.pdf",
        checksumSha256: CHECKSUM_B,
        byteSize: 98312,
        category: "cv",
      },
    ],
    handoff: {
      handoffMode: "portal-upload",
      destinationRef: "harbour-health-admissions-portal",
      encryptionProfile: "pgp",
      idempotencyKey: "decision-003:HHI",
    },
  },
];

export const universityMappingOverlaySamples: UniversityMappingOverlayV1[] = [
  {
    ...universityMappingOverlaySchemaDefaults,
    overlayId: "overlay-001",
    partnerId: "SCU",
    partnerName: "Southern Coast University",
    mappingProfileId: "southern-coast-online-v1",
    activeFrom: "2026-03-10",
    capabilityProfile: {
      transportMode: "file",
      acceptsDocumentsInline: false,
      manifestFormat: "json",
      duplicateCheckStrategy: "source-application-id",
    },
    fieldMappings: [
      {
        canonicalPath: "personalDetails.firstName",
        destinationPath: "Applicant.FirstName",
        required: true,
        transform: "identity",
        defaultValue: "Unknown",
      },
      {
        canonicalPath: "personalDetails.lastName",
        destinationPath: "Applicant.LastName",
        required: true,
        transform: "identity",
        defaultValue: "Unknown",
      },
      {
        canonicalPath: "selectedCourse.courseCode",
        destinationPath: "Application.CourseCode",
        required: true,
        transform: "uppercase",
        defaultValue: "UNKNOWN",
      },
    ],
  },
  {
    ...universityMappingOverlaySchemaDefaults,
    overlayId: "overlay-002",
    partnerId: "TIU",
    partnerName: "Tasman Institute of Technology",
    mappingProfileId: "tasman-import-v1",
    activeFrom: "2026-03-10",
    capabilityProfile: {
      transportMode: "import-workflow",
      acceptsDocumentsInline: true,
      manifestFormat: "xml",
      duplicateCheckStrategy: "email-and-course",
    },
    fieldMappings: [
      {
        canonicalPath: "personalDetails.email",
        destinationPath: "Applicant.EmailAddress",
        required: true,
        transform: "lowercase",
        defaultValue: "unknown@example.edu",
      },
      {
        canonicalPath: "selectedCourse.intakeCode",
        destinationPath: "Application.IntakePeriod",
        required: true,
        transform: "identity",
        defaultValue: "UNALLOCATED",
      },
      {
        canonicalPath: "languageTests[0].overallScore",
        destinationPath: "Compliance.IELTSOverallScore",
        required: true,
        transform: "identity",
        defaultValue: "0",
      },
    ],
  },
  {
    ...universityMappingOverlaySchemaDefaults,
    overlayId: "overlay-003",
    partnerId: "HHI",
    partnerName: "Harbour Health Institute",
    mappingProfileId: "harbour-health-rpa-v1",
    activeFrom: "2026-03-10",
    capabilityProfile: {
      transportMode: "portal-rpa",
      acceptsDocumentsInline: true,
      manifestFormat: "json",
      duplicateCheckStrategy: "email-and-course",
    },
    fieldMappings: [
      {
        canonicalPath: "personalDetails.phone",
        destinationPath: "Applicant.MobilePhone",
        required: true,
        transform: "identity",
        defaultValue: "UNKNOWN",
      },
      {
        canonicalPath: "postalAddress.formattedAddress",
        destinationPath: "Applicant.PostalAddress",
        required: true,
        transform: "join-lines",
        defaultValue: "UNKNOWN",
      },
      {
        canonicalPath: "employmentHistory[0].currentRole",
        destinationPath: "Experience.IsCurrentRole",
        required: true,
        transform: "boolean-yes-no",
        defaultValue: "No",
      },
    ],
  },
];
