export {
  AHPRA_REGISTRATION_PATTERN,
  DEFAULT_ENGLISH_MEDIUM_COUNTRY_CODES,
  isAhpraRegistration,
  SQL_AHPRA_REGISTRATION_PATTERN,
  SQL_ENGLISH_MEDIUM_COUNTRY_ALIASES,
  TRANSCRIPT_COMPLETION_PATTERN,
} from "@johncarroll/eligibility-rules";
