import type { InstitutionSuggestion } from "./types";

export const fallbackInstitutionSuggestions: InstitutionSuggestion[] = [
  {
    id: "acu",
    label: "Australian Catholic University",
    value: "Australian Catholic University",
    countryCode: "AU",
    matchText: "Australian Catholic University ACU",
  },
  {
    id: "bond",
    label: "Bond University",
    value: "Bond University",
    countryCode: "AU",
  },
  {
    id: "charles-sturt",
    label: "Charles Sturt University",
    value: "Charles Sturt University",
    countryCode: "AU",
    matchText: "Charles Sturt University CSU",
  },
  {
    id: "cqu",
    label: "CQUniversity Australia",
    value: "CQUniversity Australia",
    countryCode: "AU",
    matchText: "CQUniversity Australia CQ University CQU",
  },
  {
    id: "curtin",
    label: "Curtin University",
    value: "Curtin University",
    countryCode: "AU",
  },
  {
    id: "deakin",
    label: "Deakin University",
    value: "Deakin University",
    countryCode: "AU",
  },
  {
    id: "griffith",
    label: "Griffith University",
    value: "Griffith University",
    countryCode: "AU",
  },
  {
    id: "latrobe",
    label: "La Trobe University",
    value: "La Trobe University",
    countryCode: "AU",
    matchText: "La Trobe University Latrobe",
  },
  {
    id: "macquarie",
    label: "Macquarie University",
    value: "Macquarie University",
    countryCode: "AU",
  },
  {
    id: "monash",
    label: "Monash University",
    value: "Monash University",
    countryCode: "AU",
  },
  {
    id: "qut",
    label: "Queensland University of Technology",
    value: "Queensland University of Technology",
    countryCode: "AU",
    matchText: "Queensland University of Technology QUT",
  },
  {
    id: "rmit",
    label: "RMIT University",
    value: "RMIT University",
    countryCode: "AU",
    matchText: "RMIT University Royal Melbourne Institute of Technology",
  },
  {
    id: "melbourne",
    label: "The University of Melbourne",
    value: "The University of Melbourne",
    countryCode: "AU",
    matchText:
      "The University of Melbourne University of Melbourne Melbourne University",
  },
  {
    id: "uq",
    label: "The University of Queensland",
    value: "The University of Queensland",
    countryCode: "AU",
    matchText:
      "The University of Queensland University of Queensland UQ Queensland University",
  },
  {
    id: "sydney",
    label: "The University of Sydney",
    value: "The University of Sydney",
    countryCode: "AU",
    matchText: "The University of Sydney University of Sydney Sydney University",
  },
  {
    id: "unsw",
    label: "UNSW Sydney",
    value: "UNSW Sydney",
    countryCode: "AU",
    matchText: "UNSW Sydney University of New South Wales UNSW",
  },
  {
    id: "uts",
    label: "University of Technology Sydney",
    value: "University of Technology Sydney",
    countryCode: "AU",
    matchText: "University of Technology Sydney UTS",
  },
  {
    id: "ui",
    label: "Universitas Indonesia",
    value: "Universitas Indonesia",
    countryCode: "ID",
    matchText: "Universitas Indonesia UI University of Indonesia",
  },
  {
    id: "ugm",
    label: "Universitas Gadjah Mada",
    value: "Universitas Gadjah Mada",
    countryCode: "ID",
    matchText: "Universitas Gadjah Mada UGM Gadjah Mada University",
  },
  {
    id: "harvard",
    label: "Harvard University",
    value: "Harvard University",
    countryCode: "US",
  },
  {
    id: "mit",
    label: "Massachusetts Institute of Technology",
    value: "Massachusetts Institute of Technology",
    countryCode: "US",
    matchText: "Massachusetts Institute of Technology MIT",
  },
  {
    id: "oxford",
    label: "University of Oxford",
    value: "University of Oxford",
    countryCode: "GB",
    matchText: "University of Oxford Oxford University",
  },
  {
    id: "cambridge",
    label: "University of Cambridge",
    value: "University of Cambridge",
    countryCode: "GB",
    matchText: "University of Cambridge Cambridge University",
  },
];
